services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_USER: "books"
      DATABASE_PASSWORD: "books"
      DATABASE_HOST: "db"
      DATABASE_NAME: "books"
      DEVELOPMENT_MODE: false
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: "books"
      POSTGRES_PASSWORD: "books"
